### ISSUE TITLE
请问macOS版本用的是多少？

### ISSUE THREAD

**Issue by lian0229** [rbongIO/rbongIO-MaxSun-B760ITX-EFI#2]
我用macOS13，WiFi搜索不到设备，蓝牙应该OK。换成macOS12，连接WiFi就重启，我准备更新为最新的驱动试试，或者换成macOS11，用的也是AX211，maxsun B760itx。请问有什么好的建议吗？

**Comment by rbongIO** [comment]
不好意思，我没用WiFi
